# Generated by Django 5.2.17 on 2026-09-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_module', '0002_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
