# Generated by Django 5.2.17 on 2026-08-15 20:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('cover_url', models.URLField(blank=True, max_length=500)),
                ('current_page', models.PositiveIntegerField(default=0)),
                ('total_pages', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('current', 'Currently Reading'), ('tbr', 'To Be Read'), ('read', 'Read')], db_index=True, default='tbr', max_length=20)),
                ('rating', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('current_page__lte', models.F('total_pages'))), name='book_current_page_lte_total_pages')],
            },
        ),
        migrations.CreateModel(
            name='AestheticPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=500)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aesthetic_images', to='books.book')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('page', models.PositiveIntegerField(blank=True, null=True)),
                ('favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='books.book')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['book', 'favorite'], name='books_quote_book_id_b33aee_idx')],
            },
        ),
    ]
