# Generated by Django 5.2.17 on 2026-09-12 10:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_library_userbook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbook',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
