# Generated by Django 5.2.17 on 2026-09-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_remove_userbook_rating_book_genres_book_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='reading_goal',
            field=models.PositiveIntegerField(blank=True, help_text='Target number of books to read in a year.', null=True),
        ),
    ]
